import csv
import ast
from pathlib import Path


DATA_DIR = Path(__file__).parent.parent / "data"

PCL_TSV   = DATA_DIR / "dontpatronizeme_pcl.tsv"
TRAIN_CSV = DATA_DIR / "train_semeval_parids-labels.csv"
DEV_CSV   = DATA_DIR / "dev_semeval_parids-labels.csv"
TEST_TSV  = DATA_DIR / "task4_test.tsv"


def load_labelled_records(tsv_path: Path = PCL_TSV) -> dict[str, dict]:
    """Parse the main PCL TSV and return a dict keyed by par_id (str).

    Each value is a dict with keys:
      par_id, art_id, keyword, country_code, text, label (int, 0 or 1)

    The first three lines of the file are a disclaimer block and are skipped.
    """
    records: dict[str, dict] = {}
    with open(tsv_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("-") or not line:
                continue
            parts = line.split("\t")
            if len(parts) != 6:
                continue
            par_id, art_id, keyword, country_code, text, label_raw = parts
            label_raw_int = int(label_raw)
            records[par_id] = {
                "par_id":       par_id,
                "art_id":       art_id,
                "keyword":      keyword,
                "country_code": country_code,
                "text":         text,
                "label":        1 if label_raw_int >= 2 else 0,  # binary PCL label
                "label_raw":    label_raw_int,                   # original 0–4 score
            }
    return records


def _load_split_ids(csv_path: Path) -> list[str]:
    """Return ordered list of par_ids from a semeval split CSV."""
    ids = []
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            ids.append(row["par_id"].strip())
    return ids


def load_train() -> list[dict]:
    """Return labelled records for the training split, in original order."""
    all_records = load_labelled_records()
    return [all_records[pid] for pid in _load_split_ids(TRAIN_CSV) if pid in all_records]


def load_dev() -> list[dict]:
    """Return labelled records for the dev split, in original order."""
    all_records = load_labelled_records()
    return [all_records[pid] for pid in _load_split_ids(DEV_CSV) if pid in all_records]


def load_test() -> list[dict]:
    """Parse the unlabelled test TSV and return a list of record dicts.

    Each record has keys: test_id, art_id, keyword, country_code, text.
    No label field — predictions must be generated by the model.
    """
    records = []
    with open(TEST_TSV, encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 5:
                continue
            test_id, art_id, keyword, country_code, text = parts
            records.append({
                "test_id":      test_id,
                "art_id":       art_id,
                "keyword":      keyword,
                "country_code": country_code,
                "text":         text,
            })
    return records


def load_fine_grained_labels(csv_path: Path) -> dict[str, list[int]]:
    """Return a dict mapping par_id -> list of 7 binary PCL-category labels.

    These are available for train and dev but are not used in the primary
    binary classification task (Exercise 4/5.1). Useful for error analysis.
    """
    labels: dict[str, list[int]] = {}
    with open(csv_path, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pid = row["par_id"].strip()
            labels[pid] = ast.literal_eval(row["label"])
    return labels
